export const LIFECYCLE_EVENT = {
  SESSION_CREATED: 'SESSION_CREATED',
  POLICY_GRANT_ISSUED: 'POLICY_GRANT_ISSUED',
  PAYMENT_DECISION_CREATED: 'PAYMENT_DECISION_CREATED',
  SETTLEMENT_VERIFIED: 'SETTLEMENT_VERIFIED',
  SETTLEMENT_REJECTED: 'SETTLEMENT_REJECTED',
  SESSION_CLOSED: 'SESSION_CLOSED',
  SESSION_STATE_TRANSITION: 'SESSION_STATE_TRANSITION',
  RISK_SIGNAL: 'RISK_SIGNAL',
} as const

export type LifecycleEventType = (typeof LIFECYCLE_EVENT)[keyof typeof LIFECYCLE_EVENT]
