export const LIFECYCLE_EVENT = {
  SESSION_CREATED: 'SESSION_CREATED',
  SESSION_DENIED: 'SESSION_DENIED',
  POLICY_GRANT_ISSUED: 'POLICY_GRANT_ISSUED',
  POLICY_GRANT_DENIED: 'POLICY_GRANT_DENIED',
  PAYMENT_DECISION_CREATED: 'PAYMENT_DECISION_CREATED',
  PAYMENT_DECISION_EXPIRED: 'PAYMENT_DECISION_EXPIRED',
  PAYMENT_APPROVAL_REQUIRED: 'PAYMENT_APPROVAL_REQUIRED',
  PAYMENT_APPROVED: 'PAYMENT_APPROVED',
  PAYMENT_REJECTED: 'PAYMENT_REJECTED',
  SETTLEMENT_DETECTED: 'SETTLEMENT_DETECTED',
  SETTLEMENT_VERIFIED: 'SETTLEMENT_VERIFIED',
  SETTLEMENT_REJECTED: 'SETTLEMENT_REJECTED',
  POLICY_ENFORCEMENT_PASSED: 'POLICY_ENFORCEMENT_PASSED',
  POLICY_ENFORCEMENT_FAILED: 'POLICY_ENFORCEMENT_FAILED',
  SESSION_CLOSED: 'SESSION_CLOSED',
  SESSION_STATE_TRANSITION: 'SESSION_STATE_TRANSITION',
  RISK_SIGNAL: 'RISK_SIGNAL',
} as const

export type LifecycleEventType = (typeof LIFECYCLE_EVENT)[keyof typeof LIFECYCLE_EVENT]
