import { LIFECYCLE_EVENT } from '@parker/core'

export const SESSION_EVENTS = {
  SESSION_CREATED: 'SESSION.CREATED',
  POLICY_GRANT_ISSUED: 'POLICY.GRANT_ISSUED',
  PAYMENT_DECISION_CREATED: 'PAYMENT.DECISION_CREATED',
  SETTLEMENT_VERIFIED: 'SETTLEMENT.VERIFIED',
  SESSION_CLOSED: 'SESSION.CLOSED',
} as const

export type SessionEventType = (typeof SESSION_EVENTS)[keyof typeof SESSION_EVENTS]

const LIFECYCLE_TO_SESSION_EVENT: Partial<Record<string, SessionEventType>> = {
  [LIFECYCLE_EVENT.SESSION_CREATED]: SESSION_EVENTS.SESSION_CREATED,
  [LIFECYCLE_EVENT.POLICY_GRANT_ISSUED]: SESSION_EVENTS.POLICY_GRANT_ISSUED,
  [LIFECYCLE_EVENT.PAYMENT_DECISION_CREATED]: SESSION_EVENTS.PAYMENT_DECISION_CREATED,
  [LIFECYCLE_EVENT.SETTLEMENT_VERIFIED]: SESSION_EVENTS.SETTLEMENT_VERIFIED,
  [LIFECYCLE_EVENT.SESSION_CLOSED]: SESSION_EVENTS.SESSION_CLOSED,
}

export function toSessionEventType(eventType: string): SessionEventType | null {
  return LIFECYCLE_TO_SESSION_EVENT[eventType] ?? null
}
